name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker login --username sunny-1651 --password ${{ secrets.PAT_TOKEN }} ghcr.io
          make build VERSION="latest"
      # - name: Test
      #   run: make test
      # - name: Lint
      #   run: make lint
