name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Build
        run: |
          docker login --username sunny-1651 --password ${{ steps.generate_token.outputs.token }} ghcr.io
          make build
        env:
          VERSION: latest
      # - name: Test
      #   run: make test
      # - name: Lint
      #   run: make lint
